// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList;

namespace ToDoList.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20211217183117_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoList.UserInfo", b =>
                {
                    b.Property<string>("LoginUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginUser");

                    b.ToTable("userInfo");
                });

            modelBuilder.Entity("ToDoList.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoginUser1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TaskCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TaskDone")
                        .HasColumnType("datetime2");

                    b.Property<string>("Taskk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoginUser1");

                    b.ToTable("userTask");
                });

            modelBuilder.Entity("ToDoList.UserTask", b =>
                {
                    b.HasOne("ToDoList.UserInfo", "LoginUser")
                        .WithMany()
                        .HasForeignKey("LoginUser1");

                    b.Navigation("LoginUser");
                });
#pragma warning restore 612, 618
        }
    }
}
